// Portfolio Projects Data
const portfolioProjects = [
    // Products - Packaging Category (51 images)
    { id: 1, title: 'Product 1', category: 'packaging', image: 'image/producat/1013202511152668ecdf4ee7d36.jpg' },
    { id: 2, title: 'Product 2', category: 'packaging', image: 'image/producat/12142025151700693ed4ecd209c.jpg' },
    { id: 3, title: 'Product 3', category: 'packaging', image: 'image/producat/12142025151733693ed50de0dbd.jpg' },
    { id: 4, title: 'Product 4', category: 'packaging', image: 'image/producat/image_1770806608233.jfif' },
    { id: 5, title: 'Product 5', category: 'packaging', image: 'image/producat/image_1770806611162.jfif' },
    { id: 6, title: 'Product 6', category: 'packaging', image: 'image/producat/image_19.jfif' },
    { id: 7, title: 'Product 7', category: 'packaging', image: 'image/producat/image_34.jfif' },
    { id: 8, title: 'Product 8', category: 'packaging', image: 'image/producat/image_35.jfif' },
    { id: 9, title: 'Product 9', category: 'packaging', image: 'image/producat/image_36.jfif' },
    { id: 10, title: 'Product 10', category: 'packaging', image: 'image/producat/image_37.jfif' },
    { id: 11, title: 'Product 11', category: 'packaging', image: 'image/producat/image_38.jfif' },
    { id: 12, title: 'Product 12', category: 'packaging', image: 'image/producat/image_39.jfif' },
    { id: 13, title: 'Product 13', category: 'packaging', image: 'image/producat/image_40.jfif' },
    { id: 14, title: 'Product 14', category: 'packaging', image: 'image/producat/image_41.jfif' },
    { id: 15, title: 'Product 15', category: 'packaging', image: 'image/producat/image_42.jfif' },
    { id: 16, title: 'Product 16', category: 'packaging', image: 'image/producat/image_43.jfif' },
    { id: 17, title: 'Product 17', category: 'packaging', image: 'image/producat/image_44.jfif' },
    { id: 18, title: 'Product 18', category: 'packaging', image: 'image/producat/image_45.jfif' },
    { id: 19, title: 'Product 19', category: 'packaging', image: 'image/producat/image_46.jfif' },
    { id: 20, title: 'Product 20', category: 'packaging', image: 'image/producat/image_47.jfif' },
    { id: 21, title: 'Product 21', category: 'packaging', image: 'image/producat/image_48.jfif' },
    { id: 22, title: 'Product 22', category: 'packaging', image: 'image/producat/image_49.jfif' },
    { id: 23, title: 'Product 23', category: 'packaging', image: 'image/producat/image_50.jfif' },
    { id: 24, title: 'Product 24', category: 'packaging', image: 'image/producat/image_51.jfif' },
    { id: 25, title: 'Product 25', category: 'packaging', image: 'image/producat/image_52.jfif' },
    { id: 26, title: 'Product 26', category: 'packaging', image: 'image/producat/image_53.jfif' },
    { id: 27, title: 'Product 27', category: 'packaging', image: 'image/producat/image_54.jfif' },
    { id: 28, title: 'Product 28', category: 'packaging', image: 'image/producat/image_55.jfif' },
    { id: 29, title: 'Product 29', category: 'packaging', image: 'image/producat/image_56.jfif' },
    { id: 30, title: 'Product 30', category: 'packaging', image: 'image/producat/image_57.jfif' },
    { id: 31, title: 'Product 31', category: 'packaging', image: 'image/producat/image_59.jfif' },
    { id: 32, title: 'Product 32', category: 'packaging', image: 'image/producat/image_60.jfif' },
    { id: 33, title: 'Product 33', category: 'packaging', image: 'image/producat/image_61.jfif' },
    { id: 34, title: 'Product 34', category: 'packaging', image: 'image/producat/image_62.jfif' },
    { id: 35, title: 'Product 35', category: 'packaging', image: 'image/producat/image_63.jfif' },
    { id: 36, title: 'Product 36', category: 'packaging', image: 'image/producat/image_64.jfif' },
    { id: 37, title: 'Product 37', category: 'packaging', image: 'image/producat/image_65.jfif' },
    { id: 38, title: 'Product 38', category: 'packaging', image: 'image/producat/image_66.jfif' },
    { id: 39, title: 'Product 39', category: 'packaging', image: 'image/producat/image_67.jfif' },
    { id: 40, title: 'Product 40', category: 'packaging', image: 'image/producat/image_69.jfif' },
    { id: 41, title: 'Product 41', category: 'packaging', image: 'image/producat/image_70.jfif' },
    { id: 42, title: 'Product 42', category: 'packaging', image: 'image/producat/image_71.jfif' },
    { id: 43, title: 'Product 43', category: 'packaging', image: 'image/producat/image_72.jfif' },
    { id: 44, title: 'Product 44', category: 'packaging', image: 'image/producat/image_73.jfif' },
    { id: 45, title: 'Product 45', category: 'packaging', image: 'image/producat/image_74.jfif' },
    { id: 46, title: 'Product 46', category: 'packaging', image: 'image/producat/image_75.jfif' },
    { id: 47, title: 'Product 47', category: 'packaging', image: 'image/producat/image_76.jfif' },
    { id: 48, title: 'Product 48', category: 'packaging', image: 'image/producat/image_77.jfif' },
    { id: 49, title: 'Product 49', category: 'packaging', image: 'image/producat/image_78.jfif' },
    { id: 50, title: 'Product 50', category: 'packaging', image: 'image/producat/image_79.jfif' },
    { id: 51, title: 'Product 51', category: 'packaging', image: 'image/producat/image_80.jfif' },

    // Partners - Branding Category (8 images)
    { id: 52, title: 'Partner 1', category: 'branding', image: 'image/partinres/103120251345086904bd6406956.jpg' },
    { id: 53, title: 'Partner 2', category: 'branding', image: 'image/partinres/103120251345096904bd659346c.jpg' },
    { id: 54, title: 'Partner 3', category: 'branding', image: 'image/partinres/103120251345116904bd67234f4.jpg' },
    { id: 55, title: 'Partner 4', category: 'branding', image: 'image/partinres/103120251345126904bd689e4fb.jpg' },
    { id: 56, title: 'Partner 5', category: 'branding', image: 'image/partinres/103120251345146904bd6a4d42a.jpg' },
    { id: 57, title: 'Partner 6', category: 'branding', image: 'image/partinres/103120251345156904bd6bd92c9.jpg' },
    { id: 58, title: 'Partner 7', category: 'branding', image: 'image/partinres/image_142.jfif' },
    { id: 59, title: 'Partner 8', category: 'branding', image: 'image/partinres/image_148.jfif' }
];

// Export for use in main.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = portfolioProjects;
}
